packages:
  - apps/*
  - packages/*
  - examples/*

allowBuilds:
  '@biomejs/biome': true
  '@deepseek-ai/dsh-subprocess-local': false
  '@google/genai': false
  better-sqlite3: true
  esbuild: true
  koffi: false
  node-pty: false
  protobufjs: false
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - '@qingshaner/utility-client@1.1.0'
  - '@qingshaner/utility-server@1.1.0'
  - '@qingshaner/utility-shared@1.1.0'
  - '@qingshaner/utility@1.1.0'
  - deepagents@1.13.5
