packages:
  - apps/*
  - packages/*
  - examples/*

allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - '@qingshaner/utility-client@1.1.0'
  - '@qingshaner/utility-server@1.1.0'
  - '@qingshaner/utility-shared@1.1.0'
  - '@qingshaner/utility@1.1.0'
