packages:
  - apps/*
  - packages/*
  - examples/*

catalog:
  '@ag-ui/core': 0.0.59
  '@modelcontextprotocol/sdk': 1.30.0
  '@orpc/openapi': 2.0.0-beta.36
  '@tencentdb-agent-memory/memory-sdk-ts-v2': 1.0.1-beta.1
  drizzle-kit: 1.0.0-rc.4
  zod: 4.6.5

allowBuilds:
  '@biomejs/biome': true
  '@deepseek-ai/dsh-subprocess-local': false
  '@google/genai': false
  better-sqlite3: true
  esbuild: true
  koffi: false
  node-pty: false
  protobufjs: false
  simple-git-hooks: true

minimumReleaseAgeExclude:
  - '@qingshaner/utility-client@1.1.0'
  - '@qingshaner/utility-server@1.1.0'
  - '@qingshaner/utility-shared@1.1.0'
  - '@qingshaner/utility@1.1.0'
  - deepagents@1.13.5
  - '@tanstack/ai-client@0.32.0'
  - '@tanstack/ai@0.55.0'
